### PR TITLE
Add Keepalived support for can_rach:ipAddress

### PR DESCRIPTION
**Pull request by OAMchronicle**
## Description

**What type of PR is this ?:**

Add Keepalived support for can_rach:ipAddress

### CODE REVIEW

**Comment by renyunkang** [comment]
Thanks! but this feature is already complete.

- https://github.com/openelb/openelb/blob/8d6aca076258c8def59ae23dd0537df2abc6d8dd/pkg/speaker/vip/keepalived.go#L256

**Comment by OAMchronicle** [comment]
> [APPROVALNOTIFIER]此请购单未经批准
> 
> 此拉取请求已由以下人员批准：[OAMchronicle](https://github.com/openelb/openelb/pull/452#)要完成[拉式请求流程](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)，请在PR审核后分配zheng 1。您可以在准备好后通过在评论中写入`/assign @zheng1`将PR分配给他们。
> 
> 这个
> 机器人接受的命令的完整列表可以在这里找到。
> 
> 在
> 这些文件中，需要获得审批人的批准：
> * [所有者](https://github.com/openelb/openelb/blob/master/OWNERS)
> 
> 审批人可以在评论中写入`/approve`来表示他们的批准批准人可以通过在注释中写入`/approve cancel`来取消批准

This does not work in 0.6.0, it will treat can_rach: ipAddress as ifaceName

**Comment by renyunkang** [comment]
I figured out what the problem was, thank you again.

I think it is better to modify the content in the function: `func (k *keepAlived) ConfigureWithEIP(config speaker.Config, deleted bool) error`

**Comment by OAMchronicle** [comment]
> Thanks! but this feature is already complete.
> 
> * https://github.com/openelb/openelb/blob/8d6aca076258c8def59ae23dd0537df2abc6d8dd/pkg/speaker/vip/keepalived.go#L256

I have resubmitted https://github.com/openelb/openelb/pull/453

**Pull request closed without merging**
