### PR TITLE
feat(bgp): Add configuration for DefinedSets

### PR DESCRIPTION
**Pull request by amalthundiyil**
## Description
Added configuration for `DefinedSets` and its child elements.

## Related links:
- #267 

Signed-off-by: Amal Thundiyil <amal.s.thundiyil@gmail.com>

### CODE REVIEW

**Comment by renyunkang** [comment]
Thanks for your contribution!!!

**Comment by chaunceyjiang** [comment]
I have a question. Can we put the configuration in the configmap like coreDNS?

https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options

**Comment by chaunceyjiang** [comment]
Maybe it's not just the goBGP policy configuration. Can all goBGP configurations be placed in the ConfigMap so that we can support all goBGP features?

**Comment by chaunceyjiang** [comment]
> I have a question. Can we put the goBGP policy configuration in the ConfigMap like coreDNS?
> 
> https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options

What do you think about it？ @amal-thundiyil @renyunkang

**Comment by renyunkang** [comment]
> > I have a question. Can we put the goBGP policy configuration in the ConfigMap like coreDNS?
> > https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#coredns-configmap-options
> 
> What do you think about it？ @amal-thundiyil @renyunkang

Very good, simpler and more convenient than the previous design.

**Pull request closed without merging**
