### PR TITLE
refine README and update the doc links

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Signed-off-by: FeynmanZhou <feynman@kubesphere.io>

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
Hi team @liangyuanpeng @zheng1 @renyunkang ,

Can anyone help me to review it? 

Thanks

**Review by liangyuanpeng — APPROVED** [review]
LGTM,Thanks for your work.

**Comment by FeynmanZhou** [comment]
> /approve

It looks you need to add a label `/lgtm` there

**Pull request merged**
