### PR TITLE
fix: better EIP verification for `layer2` and `vip` mode

### LINKED ISSUE #272: Incomplete eip verification in layer2 or vip mode
When the eip configured in layer2 or vip mode and the specified NIC are not in the same network segment, an error should be reported instead of being created successfully.
/kind bug

### PR DESCRIPTION
**Pull request by amalthundiyil**
## Description
With this PR, when the EIP configured in `layer2` or `vip` mode and the specified NIC are not in the same network segment, an error is reported instead of being created successfully. 

## Related Links
- Fixes #272 

Signed-off-by: Amal Thundiyil <amal.s.thundiyil@gmail.com>

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
Can you help review？
/cc @renyunkang

**Comment by renyunkang** [comment]
Can we do this in a webhook. I updated the issue description, you can take a look again. We can solve the layer2 mode first.

**Comment by Gapodo** [comment]
Hi,
as I've just stumbled across #272 (been looking for something different regarding vip) and seen that there is already an implementation on the way. I wanted to chime in and give an opinion on the verification... some hosting-providers hand out vips not belonging to the same L2 domain as the base interface, so an option to allow for suppressing this check would be needed to use it in some cases (currently netcup, hetzner and digital ocean come to mind when thinking about "bigger" players that I am aware of using /32s in different L2 domains)

**Comment by richard-fairthorne** [comment]
This is preventing me from using openelb. There is no reason that we cannot use layer2 with IP's in a different segment from the interface.

**Pull request closed without merging**
