### PR TITLE
add CIDR range for NICs in layer2

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>

add CIDR range for NICs in layer2
## Description

**What type of PR is this ?:**

/feature

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
@renyunkang

**Comment by chaunceyjiang** [comment]
@amal-thundiyil

**Comment by amal-thundiyil** [comment]
LGTM! Thanks 👍

**Pull request merged**
