### PR TITLE
fix All Contributors badge

### LINKED ISSUE #256: The All-Contributor badge is broken and the statistics is not complete
- [ ] The All-Contributor badge is broken:

image

- [ ] I see there is only one contributor in README, is there a way to add all contributors?

### PR DESCRIPTION
**Pull request by renyunkang**
Signed-off-by: renyunkang <renyun_kang@163.com>
fix #256
/assign @zheng1

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
Is there any way to add all contributors?

**Comment by renyunkang** [comment]
I referenced https://github.com/jenkinsci/ui-ux-hackfest-2020/issues/1.
Maybe it can be achieved through a config file.

**Comment by chaunceyjiang** [comment]
https://github.com/apps/allcontributors
@all-contributors please add @chaunceyjiang  for infrastructure, tests and code

**Pull request merged**
