### PR TITLE
Update constant.go

### PR DESCRIPTION
**Pull request by OAMchronicle**
fix: https://github.com/openelb/openelb/issues/370

### CODE REVIEW

**Comment by renyunkang** [comment]
It is recommended to use configmap to configure custom images. https://github.com/openelb/openelb/pull/285

**Comment by OAMchronicle** [comment]
What I mean is that there is a problem with this image。Why don't we modify the default image？

**Comment by renyunkang** [comment]
It is not the best way to solve this problem. I think we should maintain a fork of the kube-keepalived-vip repository from https://github.com/aledbf/kube-keepalived-vip.

If the image you built can solve your problem, you can first use configmap to modify the custom image.

**Comment by OAMchronicle** [comment]
I started from https://github.com/aledbf/kube-keepalived-vip fork https://github.com/oamchronicle/kube-keepalived-vip . Partially modified the code and updated the dependent package version.

**Comment by renyunkang** [comment]
> I started from https://github.com/aledbf/kube-keepalived-vip fork https://github.com/oamchronicle/kube-keepalived-vip . Partially modified the code and updated the dependent package version.

Can you commit your changes to https://github.com/openelb/kube-keepalived-vip?

**Comment by OAMchronicle** [comment]
> > 我从[https：//github.com/aledbf/kube-keepalived-vip](https://github.com/aledbf/kube-keepalived-vip)fork[https：//github.com/oamchronicle/kube-keepalived-vip](https://github.com/oamchronicle/kube-keepalived-vip)开始。部分修改了代码并更新了依赖包版本。
> 
> 你能把修改提交到[https：//github.com/openelb/kube-keepalived-vip](https://github.com/openelb/kube-keepalived-vip)吗？

https://github.com/openelb/kube-keepalived-vip/pull/1

**Comment by renyunkang** [comment]
> [openelb/kube-keepalived-vip#1](https://github.com/openelb/kube-keepalived-vip/pull/1)

Thanks!

**Pull request closed without merging**
